use_frameworks!

platform :ios, '10.0'

target 'ZLStateView_Example' do
  pod 'ZLStateView', :path => '../'
  pod 'DZNEmptyDataSet'
  pod 'ZLPopView'
  pod 'FPRefresh'
#  pod "PromiseKit", "~> 8"

  target 'ZLStateView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
